---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    microservice: '{{ microservice }}'
    port: '{{ port }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u deepthicshetty@gmail.com -p SuperEasy123! thisisjfrogdemo.jfrog.io
    
    - name: pull an image
      shell: docker pull thisisjfrogdemo.jfrog.io/cicd-docker/microservicebasedapp/{{ microservice }}:v1.0.{{ build_number }}

    - name: remove container
      shell: docker rm -f {{ microservice }}
        
    - name: create a application container
      shell: docker run -id --name {{ microservice }} -p {{ port }}:{{ port }} --network new-bridge-network thisisjfrogdemo.jfrog.io/cicd-docker/microservicebasedapp/{{ microservice }}:v1.0.{{ build_number }} 
 
