apiVersion: v1
kind: Service
metadata:
  name: payments
  labels: { app: payments }
spec:
  selector: { app: payments }
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
