apiVersion: v1
kind: Service
metadata:
  name: products
  labels: { app: products }
spec:
  selector: { app: products }
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
